self.addEventListener("install",e=>{
    e.waitUntil(
        caches.open("microoss-cache")
        .then(cache=>cache.addAll([
            "/",
            "/index.php",
            "/assets/css/style.css"
        ]))
    );
});